### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by valknut89** [panbachi/wordclock#11]
Is it possible to change brightness in 4.0.1 ?
I only find the option in the "led.cpp" but I am not sure if it the right one.

Thx

**Comment by napsio** [comment]
In version 4.0.1 you can only change the brightness by changing the color to a lighter or darker one.

**Comment by SehlingS** [comment]
I'm a little bit confuesd.
I have cloned or download the master branch and with that version, i can addjust the brightness depending in on current.
But now i have seen that the version 4.0.1 under Releases has a other gui.cpp file without that function.
What is now the newest version and why has the master branch a other state as the last release.
Sorry but I'm a newbie here at github ;-)

**Comment by napsio** [comment]
The master branch is newer and has additional functionality, but has still some bugs. When the bugs were fixed, it will be released as version 5.0.0. For now version 4.0.1 is the stable release.

**Comment by SehlingS** [comment]
OK Thank you, i use the master branch, so I'm a beta tester ;-). But it works without any problems for now.
One additional thing, is it possibile to deactivate the blue led at the wemos? In one of my clock it shines out of it.
And one last thing, can you add the acutal version to the footer of the web gui? That helps to identify the installed version.

**Comment by valknut89** [comment]
> In version 4.0.1 you can only change the brightness by changing the color to a lighter or darker one.

i tried the brightness control in master branch. i tested with 2000 mA and 10%, 100%. But the leds didn't change brightness. I tried restart too without success. Is there a trick or must I connect the led stripes directly to 5V supply ? I connected the stripe to wemos 5V GND and D4

**Comment by SehlingS** [comment]
it works for me like you it should. I have conncet the stripes only to the wemos 5v, Gnd and D4 Pin.

**Comment by valknut89** [comment]
I checked my ESP, its not a wemos D1. It is a D1 ESP8266MOD 12-F. Maybe thats the Problem? Do you have any Ideas?

**Comment by SehlingS** [comment]
i have the same one. without any problems.
https://de.aliexpress.com/item/32651747570.html?spm=a2g0s.9042311.0.0.17dc4c4d61v0P4

**Comment by valknut89** [comment]
> i have the same one. without any problems.
> https://de.aliexpress.com/item/32651747570.html?spm=a2g0s.9042311.0.0.17dc4c4d61v0P4

Your Brightness Settings working? Pls check 0% 10% till 100% if brightness is changing Top. Thx

Which stripes do you use?

**Comment by SehlingS** [comment]
i use this one 
https://de.aliexpress.com/item/32682015405.html?spm=a2g0s.9042311.0.0.17dc4c4d61v0P4
IP 30 60LED/m

it is changing, but only till 60% because i have set it to 1000mA.
I can adjust it in 5% steps.

**Comment by valknut89** [comment]
which version do you use? I have only 10% steps Which version of fastLED library do you use?

which board config do you use in Arduino IDE?

**Comment by SehlingS** [comment]
i use the newest libs which are availble in Arduino IDE. 
Boardconfig is wemos d1 but if you select the wrong one, i got an error message.

I think is use a mix branch some parts from the master and some parts from the @ibrot fork.
But only because of the problems with the automatic time zone.

The brightness works also before i start to mix with the "10% Version"

**Comment by SehlingS** [comment]
i can create you a bin file from my local programm. So, you can test if it works with that one.
What grid do you use? 11x11 with de_De ?

**Comment by valknut89** [comment]
Ok. Thx I will try. I have a own Layout. So can send me your Version, that's best

**Comment by SehlingS** [comment]
sorry for the delay, you can use my fork. This version is working for me without any problems.
Automatic tiem zone and brightness is wirking well for me in germany. ( +1)

**Comment by valknut89** [comment]
Found the issue. I used DE_alt. In the cpp the line ''FastLED.setBrightness(Config::brightness * 255);'' was missing in master-branch and 4.0.1
