### ISSUE TITLE
Funktioniert der 11x10 Modus schon? :) 

### ISSUE THREAD

**Issue by SkylightXD** [panbachi/wordclock#17]
Hi Panbachi,

funktioniert der 11x10 Modus schon richtig?
Ich habe es gerade getestet, aber irgendwie sah die Anzeige komisch aus ;) 
Oder funktioniert die Eckenwahl für die erste LED nicht? 
Kann ich den Minutenzähler auch ausschalten oder schreibe ich den ans Ende und schneide den Streifen ab? :)

Sorry für die vielen Fragen, ich hoffe es hilft dir :)

Grüße

**Comment by SehlingS** [comment]
Ich habe selber eine 11x10 Varaiante am Laufen. Minuten LED einfach ans Ende, dann passt das ;-).
ich beginne unten links.

**Comment by WolfgangFranke** [comment]
@SkylightXD can you please check #23 , ich habe damit jetzt eine sinnvolle Anzeige (läuft im 11x10 Modus, die erste LED ist top-left = oben-links).

**Comment by SkylightXD** [comment]
Bei mir läuft jetzt die 11x10 mit der ersten LED links unten, das klappt :)
