### ISSUE TITLE
Frage zu Minuten LED´s

### ISSUE THREAD

**Issue by obkram** [panbachi/wordclock#7]
Hallo lieber Entwickler,

vorab bedanke ich mich bei Ihnen für die Möglichkeit dieses tolle Projekt nachbauen zu dürfen.

Hierbei handelt es sich weniger um einen Issue sondern mehr um eine Anfrage.

**Mein Aufbau**:
In meinem Fall habe ich ein Grid von 11x11 LEDs, Minutenposition after und Start LED unten links bei Draufsicht gewählt.
Auf vier zusätzliche LED habe ich wegen der schmalen Bauform des RIBBA Rahmens verzichtet.

Meine Frage wäre nun ob ich evtl. in der Konfiguration die Position der Minuten LEDs selbst ändern kann und wenn ja wo. Bei dem von Ihnen vorgegebenen Grid Layout besteht bei einer LED Bestückung von 11x11 LEDs die unterste Zeile aus der Buchstabenreihe **"E-V-F-X-R-N-Z-S-L-P-I"**.
Dies scheint ja ein optischer Platzhalter zu sein da sich hieraus keine Wörter Bilden lassen. Ich hatte mir vorgestellt hier die Positionen **"F R Z L"** für die Minuten zu missbrauchen.

Sollte dies möglich sein dann würde ich mich über einen Hinweis freuen. Ansonsten Anfrage bitte einfach ignorieren und schliessen. Vielen Dank im Voraus.

LG Sven O.

**Comment by obkram** [comment]
Hallo nochmal,

ich habe es für mich jetzt zumindest schon einmal soweit eingegrenzt das ich bei Änderung der ersten Minuten-LED-Position in der Zeile 62 in der Datei de_DE.cpp die Minutenanzeige an die Position 112 bekomme.
Vielleicht hat ja jemand eine Idee wie ich die Formel ...

_for(int s = (NUM_LEDS - _**"neue LED POSITION"**_); s < (NUM_LEDS _**"neue LED POSITION"**_ + singleMinute); s++)_ 

...so abändern kann das die singleMinute nicht an der Position bspw. 112-115 angezeigt werden sondern an den Positionen 112, 114, 116 und 118. Also immer eine singleMinute + ein Platzhalter für die folgende LED.

![Nachrichten-Bild(3586913851)](https://user-images.githubusercontent.com/33160929/96553281-3a371100-12b5-11eb-884a-090790ee1b63.jpeg)

LG Sven O.

**Comment by napsio** [comment]
Hi,

du kannst mal folgendes probieren (ungetestet):

```c
  if(GRID_SINGLE_MINUTES == 1) {
	// single minutes
        if(singleMinute >= 1) {
	  Led::ids[112].setRGB(Config::color_fg.r, Config::color_fg.g, Config::color_fg.b);
        }
        if(singleMinute >= 2) {
	  Led::ids[114].setRGB(Config::color_fg.r, Config::color_fg.g, Config::color_fg.b);
        }
        if(singleMinute >= 3) {
	  Led::ids[116].setRGB(Config::color_fg.r, Config::color_fg.g, Config::color_fg.b);
        }
        if(singleMinute >= 4) {
	  Led::ids[118].setRGB(Config::color_fg.r, Config::color_fg.g, Config::color_fg.b);
        }
  } else {
	for(int s = 0; s < singleMinute; s++) {
	  Led::ids[s].setRGB(Config::color_fg.r, Config::color_fg.g, Config::color_fg.b);
	}
  }
```
Ist zwar nicht die schönste Lösung, müsste aber funktionieren :)

**Comment by obkram** [comment]
Hallo napsio,

vielen Dank für die schnelle Antwort. Ich habe es sofort getestet und es funktioniert einwandfrei. Ich musste lediglich die LED IDs auf 2,4,6 und 8 abändern. Dies hat scheinbar seinen Ursprung darin, das ich von unten links anfangen muss zu zählen, da dort mein Einspeisepunkt ist.
Vielleicht könnte das ja mit den Auswahloptionen wie unten angegeben von panbachi in den Master mit aufgenommen werden.

 * 0: before
 * 1: last
 * 2: after
 */
#define GRID_SINGLE_MINUTES 1


Vielen Dank für die Hilfe napsio.

LG Sven O.

**Comment by obkram** [comment]
Hallo napsio,

anbei sende ich dir ein Bild wie die Darstellung bei mir nun aussieht. Danke nochmal.
![EDF2A85E-B3F9-4948-91A5-2BAE84EF430C](https://user-images.githubusercontent.com/33160929/97092563-3c96c380-1645-11eb-814f-b72a37c05830.jpeg)


LG Sven O.
