### ISSUE TITLE
farylink xxx AP visibale after Connection to a Network

### ISSUE THREAD

**Issue by SehlingS** [panbachi/wordclock#9]
Hey, 
my Wordclock is connceted to my 2.4 Ghz Wlan but the own unsecured AcessPoint is still visible.
But not the one named with wordclock the name is farylink XXXX. How can i disabel this wlan ap?
I have found that Thread with maybe a solution: https://forum.arduino.cc/index.php?topic=493972.0

best regards
Sascha

**Comment by SehlingS** [comment]
i have solved the problem by adding the following row to the wifi.cpp file.
WiFi.mode(WIFI_STA);

Then there is only 1 AP (Wordclock) avalible and after setting the wlan password and ssid, all networks are closed.

**Comment by valknut89** [comment]
I had this too. I changed it. Now my AP shows only up, if I press the reset button of my D1 twice. Because I added an RTC Chip, so that I dont need Wifi permanently.

**Comment by SehlingS** [comment]
> I had this too. I changed it. Now my AP shows only up, if I press the reset button of my D1 twice. Because I added an RTC Chip, so that I dont need Wifi permanently.

Can you share us your solution?

**Comment by valknut89** [comment]
wifi.cpp:

```cpp
#include <ESP8266WiFi.h>
#include <WiFiManager.h>
#include <DoubleResetDetector.h>
#include "wifi.h"

// Number of seconds after reset during which a 
// subseqent reset will be considered a double reset.
#define DRD_TIMEOUT 10

// RTC Memory Address for the DoubleResetDetector to use
#define DRD_ADDRESS 0

DoubleResetDetector drd(DRD_TIMEOUT, DRD_ADDRESS);

void Wifi::setup() { 

WiFi.hostname("WordClock");
WiFiManager wifiManager;
 if (drd.detectDoubleReset()) {
    Serial.println("Double Reset Detected");
    wifiManager.autoConnect("WordClock");
  } else {
    Serial.println("No Double Reset Detected");
  }
}

void Wifi::reset() {
  WiFi.disconnect(true);
}
```

**Comment by valknut89** [comment]
time.cpp:

```cpp
#include <Arduino.h>
#include <NTPClient.h>
#include <WiFiUdp.h>
#include <ESP8266WiFi.h>
#include "time.h"
#include "grid.h"
#include "utcOffset.h"

//RTC
#include <Wire.h>
#include "RTClib.h"
 
RTC_DS3231 rtc;
 
char daysOfTheWeek[7][12] = {"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"};

 
void Time::setup() {
Time::ntpClient.setTimeOffset(3600);  
Time::ntpClient.begin();
Time::ntpClient.update();

#ifndef ESP8266
  while (!Serial); // for Leonardo/Micro/Zero
#endif
 
  if (! rtc.begin()) {
    Serial.println("Couldn't find RTC");
  }
 
}

void Time::loop() {
 int h;
 int m; 
 int s;
  if (WiFi.status() == WL_CONNECTED) {
  Time::ntpClient.update();
  h = Time::ntpClient.getHours();
  m = Time::ntpClient.getMinutes();
  s = Time::ntpClient.getSeconds();
  if (rtc.begin()) {
    rtc.adjust(DateTime(2014, 1, 21, h, m, s));}
}

  else { if (rtc.begin()) {       
DateTime now = rtc.now();
       h = now.hour();
       m = now.minute();
       } }
  


  if(m != Time::minute) {
    if(m == 0 && h == Time::hour) {
      h = (h + 1) % 24;
    }

    Time::hour = h;
    Time::minute = m;
    
Grid::setTime(Time::hour, Time::minute);
    Time::ntpClient.setTimeOffset(3600);

  }
}

int Time::hour = -1;
int Time::minute = -1;
WiFiUDP Time::udp;
NTPClient Time::ntpClient = NTPClient(Time::udp);
```

**Comment by napsio** [comment]
@SehlingS Thanks for the tip. It seems to depend on the version of the WiFiManger library. I could not reproduce it with an older version of the lib.

@valknut89 Thanks for your code. What RTC module do you use for the clock?

**Comment by SehlingS** [comment]
Can you add this part to your wifi.cpp file.
WiFi.mode(WIFI_STA);

I think that has no negative effect ;-).

**Comment by valknut89** [comment]
> @SehlingS Thanks for the tip. It seems to depend on the version of the WiFiManger library. I could not reproduce it with an older version of the lib.
> 
> @valknut89 Thanks for your code. What RTC module do you use for the clock?

The DS3231

**Comment by napsio** [comment]
> Can you add this part to your wifi.cpp file.
> WiFi.mode(WIFI_STA);
> 
> I think that has no negative effect ;-).

I've added the line to the master branch.

**Comment by SehlingS** [comment]
Thx

**Comment by p3moto** [comment]
i downloadad the files 4.0.1 an changed the code here:

> 
> 
> wifi.cpp:
> 
> ```c++
> #include <ESP8266WiFi.h>
> #include <WiFiManager.h>
> #include <DoubleResetDetector.h>
> #include "wifi.h"
> 
> // Number of seconds after reset during which a 
> // subseqent reset will be considered a double reset.
> #define DRD_TIMEOUT 10
> 
> // RTC Memory Address for the DoubleResetDetector to use
> #define DRD_ADDRESS 0
> 
> DoubleResetDetector drd(DRD_TIMEOUT, DRD_ADDRESS);
> 
> void Wifi::setup() { 
> 
> WiFi.hostname("WordClock");
> WiFiManager wifiManager;
>  if (drd.detectDoubleReset()) {
>     Serial.println("Double Reset Detected");
>     wifiManager.autoConnect("WordClock");
>   } else {
>     Serial.println("No Double Reset Detected");
>   }
> }
> 
> void Wifi::reset() {
>   WiFi.disconnect(true);
> }
> ```


my clock just shows the white "E" für a second an then jumps du a random time... then the clock is not reachabele for wifi anymore... not listed in the router or shows any register-wifi for login

the time.cpp seems to be ok. Tested it again and pnly changed the time.cpp code. Everything fine




und wieso schrieben wir hier eigentlich alle auf englisch,...? sind doch eh nur deutschsprachige Fontplatten in dem Code ???

**Comment by valknut89** [comment]
OK, dann halt mal in Deutsch. Also: Die angepasste wifi.cpp sorgt dafür, dass der Access Point des ESP nur sichtbar wird, wenn man nach Stromzufuhr innerhalb von 10s zweimal den Reset-Taster drückt. Ist eine Optimierung, die ich für mich als gut befunden habe, mehr nicht. Kannst du also im Originalzustand belassen.
Was die Time.cpp angeht:
Das Skript, was ich ergänzt habe, sieht einen zusätzlichen RTC-Chip DS3231 vor, der die aktuelle Zeit speichert und auch bei Stromunterbrechung und OHNE WLAN die Zeit korrekt anzeigt. Hast du diesen Chip nicht, ist der Großteil des Skriptes auch für dich gar nicht relevant.

Zu deinem Problem: 
Mach mal folgendes: Spiele dir die aktuelle Version 4.0.1 auf und setze die Zeitzone im Web-Interface manuell, wenn möglich. Wenn das nicht geht, dann editiere die time.cpp mal wie folgt:

```
#include <Arduino.h>
#include <NTPClient.h>
#include <WiFiUdp.h>

#include "time.h"
#include "grid.h"

void Time::setup() {
  Time::ntpClient.setTimeOffset(3600);
  Time::ntpClient.begin();
  Time::ntpClient.update();
}

void Time::loop() {
  Time::ntpClient.update();

  int h = Time::ntpClient.getHours();
  int m = Time::ntpClient.getMinutes();

  if(m != Time::minute) {
	if(m == 0 && h == Time::hour) {
		h = (h + 1) % 24;
	}
	
    Time::hour = h;
    Time::minute = m;
    Grid::setTime(Time::hour, Time::minute);
    Time::ntpClient.setTimeOffset(3600);
  }
}

int Time::hour = -1;
int Time::minute = -1;
WiFiUDP Time::udp;
NTPClient Time::ntpClient = NTPClient(Time::udp);
```

**Comment by p3moto** [comment]
@valknut89 vielen lieben Dank für die ausführlichen und verständlichen Erklärungen :)
